# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update README.md
      run: node index.js > README.md
    - name: Commit change & Push
      run: |
        git config user.name 'oranzhevyy[bot]'
        git config user.email 'thatoranzhevyy@gmail.com'
        git commit -am "oranzhevyy-bot: update README.md automatically"
        git push
